# Generated by Django 5.1.3 on 2025-01-29 19:11

import django.db.models.deletion
import sortedm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('note', models.CharField(blank=True, default='', max_length=128, verbose_name='примечание')),
                ('description', models.TextField(blank=True, default='', max_length=512, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('file', models.FileField(upload_to='assets/%Y/%m/%d/', verbose_name='файл')),
                ('tag', models.CharField(blank=True, default=' ', max_length=32, verbose_name='тэг')),
            ],
            options={
                'verbose_name': 'ассет',
                'verbose_name_plural': 'ассеты',
            },
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('note', models.CharField(blank=True, default='', max_length=128, verbose_name='примечание')),
                ('description', models.TextField(blank=True, default='', max_length=512, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('icon', models.CharField(max_length=64, verbose_name='fa-иконка')),
                ('detail', models.TextField(max_length=512, verbose_name='информация')),
            ],
            options={
                'verbose_name': 'контакты: данные',
                'verbose_name_plural': 'контакты: данные',
            },
        ),
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('note', models.CharField(blank=True, default='', max_length=128, verbose_name='примечание')),
                ('description', models.TextField(blank=True, default='', max_length=512, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('icon', models.CharField(max_length=64, verbose_name='fa-иконка')),
                ('url', models.URLField(verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'контакты: ссылка',
                'verbose_name_plural': 'контакты: ссылки',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('note', models.CharField(blank=True, default='', max_length=128, verbose_name='примечание')),
                ('description', models.TextField(blank=True, default='', max_length=512, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('text', models.TextField(max_length=255, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'промо блок',
                'verbose_name_plural': 'промо блоки',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('note', models.CharField(blank=True, default='', max_length=128, verbose_name='примечание')),
                ('description', models.TextField(blank=True, default='', max_length=512, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('icon', models.CharField(max_length=64, verbose_name='fa-иконка')),
            ],
            options={
                'verbose_name': 'услуги: строка',
                'verbose_name_plural': 'услуги: строки',
            },
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('note', models.CharField(blank=True, default='', max_length=128, verbose_name='примечание')),
                ('description', models.TextField(blank=True, default='', max_length=512, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('message', models.TextField()),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='home.asset', verbose_name='аватар')),
                ('bg_image', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='home.asset', verbose_name='паттерн')),
            ],
            options={
                'verbose_name': 'обо мне',
                'verbose_name_plural': 'обо мне',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('note', models.CharField(blank=True, default='', max_length=128, verbose_name='примечание')),
                ('description', models.TextField(blank=True, default='', max_length=512, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('map_widget', models.TextField(blank=True, default='', max_length=2048, verbose_name='виджет карты')),
                ('details_list', sortedm2m.fields.SortedManyToManyField(help_text=None, to='home.contactdetail', verbose_name='список данных')),
                ('link_list', sortedm2m.fields.SortedManyToManyField(help_text=None, to='home.contactlink', verbose_name='список ссылок')),
            ],
            options={
                'verbose_name': 'контакты',
                'verbose_name_plural': 'контакты',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('note', models.CharField(blank=True, default='', max_length=128, verbose_name='примечание')),
                ('description', models.TextField(blank=True, default='', max_length=512, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('copyright_text', models.TextField(max_length=512, verbose_name='копирайт')),
                ('bg_pattern', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='home.asset', verbose_name='паттерн')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='home.asset', verbose_name='лого')),
            ],
            options={
                'verbose_name': 'футер',
                'verbose_name_plural': 'футеры',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('note', models.CharField(blank=True, default='', max_length=128, verbose_name='примечание')),
                ('description', models.TextField(blank=True, default='', max_length=512, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('items', sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='+', to='home.asset', verbose_name='Примеры')),
            ],
            options={
                'verbose_name': 'портфолио',
                'verbose_name_plural': 'портфолио',
            },
        ),
        migrations.CreateModel(
            name='ServiceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('note', models.CharField(blank=True, default='', max_length=128, verbose_name='примечание')),
                ('description', models.TextField(blank=True, default='', max_length=512, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('image_position', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='L', max_length=1, verbose_name='расположение изображения')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='home.asset', verbose_name='изображение')),
                ('items', sortedm2m.fields.SortedManyToManyField(help_text=None, to='home.serviceitem', verbose_name='строки')),
            ],
            options={
                'verbose_name': 'услуги: блок',
                'verbose_name_plural': 'услуги: блоки',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('note', models.CharField(blank=True, default='', max_length=128, verbose_name='примечание')),
                ('description', models.TextField(blank=True, default='', max_length=512, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('items', sortedm2m.fields.SortedManyToManyField(help_text=None, to='home.serviceblock', verbose_name='блоки')),
            ],
            options={
                'verbose_name': 'услуги',
                'verbose_name_plural': 'услуги',
            },
        ),
        migrations.CreateModel(
            name='StartScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('note', models.CharField(blank=True, default='', max_length=128, verbose_name='примечание')),
                ('description', models.TextField(blank=True, default='', max_length=512, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('primary_text', models.TextField(max_length=255, verbose_name='основной текст')),
                ('secondary_text', models.TextField(max_length=255, verbose_name='дополнительный текст')),
                ('bg_pattern', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='home.asset', verbose_name='паттерн')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='home.asset', verbose_name='лого')),
            ],
            options={
                'verbose_name': 'стартовый экран',
                'verbose_name_plural': 'стартовые экраны',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('note', models.CharField(blank=True, default='', max_length=128, verbose_name='примечание')),
                ('description', models.TextField(blank=True, default='', max_length=512, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('title', models.TextField(max_length=255, verbose_name='название страницы')),
                ('is_active', models.BooleanField(default=False, verbose_name='сделать активной')),
                ('show_nav_bar', models.BooleanField(default=True, verbose_name='показывать понель навигации')),
                ('about_me', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.aboutme', verbose_name='обо мне')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.contacts', verbose_name='контакты')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.footer', verbose_name='футер')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='home.asset', verbose_name='иконка (png)')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='home.asset', verbose_name='лого панели навигации')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.portfolio', verbose_name='портфолио')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.promo', verbose_name='промо блок')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.services', verbose_name='услуги')),
                ('start_screen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.startscreen', verbose_name='стартовый экран')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
