# Generated by Django 5.1.3 on 2024-11-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
