# Generated by Django 5.1.3 on 2024-11-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='contactlink',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='footer',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='promo',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='startscreen',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='serviceblock',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='описание'),
        ),
    ]
