services:
  db:
    image: postgres:16.5
    container_name: personal-page-db
    restart: always
    shm_size: 300mb
    volumes:
      - "page-db:/var/lib/postgresql/data/"
    env_file:
      - .env
  app:
    image: personal-page-app:${APP_VERSION:-latest}
    container_name: personal-page-app
    restart: always
    shm_size: 300mb
    command: "uv run gunicorn -b 0.0.0.0:8000 conf.wsgi"
    volumes:
      - "page-static-files:/home/app/files/static"
      - "page-media-files:/home/app/files/media"
    env_file: .env
    depends_on:
      - db
  nginx:
    image: nginx:1.27
    container_name: personal-page-nginx
    restart: always
    shm_size: 300mb
    ports:
    - "443:443"
    volumes:
      - "./certs/:/etc/nginx/certs"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "page-static-files:/var/html/static"
      - "page-media-files:/var/html/media"
    depends_on:
      - app


volumes:
  page-static-files:
    external: true
  page-media-files:
    external: true
  page-db:
    external: true
